### Create a new report
POST http://localhost:3001/api/reports
Content-Type: application/json

{
  "price": 20000,
  "make": "ford",
  "model": "mustang",
  "year": 1982,
  "longitude": 45,
  "latitude": 45,
  "mileage": 5000
}

### Approve an existing report
PATCH http://localhost:3001/api/reports/9
Content-Type: application/json

{
  "approved": true
}

### Get an estimate for existing vehicle
GET http://localhost:3001/api/reports?make=ford&model=mustang&longitude=45&latitude=45&mileage=30000&year=1981